### ISSUE TITLE
get_birthday - празна стойност

### ISSUE THREAD

**Issue by veskoto** [ivantcholakov/egn#1]
Здравей,
благодаря за кода!
Имаш ли идея защо на някои ЕГН-та get_birthday връща празна стойност
``8509143983 - Birthday is``

**Comment by veskoto** [comment]
След премахване на 
```
        if (self::is_foreigner($string)) {
            return null;
        }
```
се оправя :+1:

**Comment by ivantcholakov** [comment]
Оправено. Благодаря.

https://github.com/ivantcholakov/egn/releases/tag/v1.50.4
